# Gitlab Container Registry'a push ettiğimiz image
# Packages & Registries > Container Registry
image: registry.gitlab.com/akinakalin/laravel-deploy-tests:latest

stages:
  - tests
  - deploy

tests:
  stage: tests
  script:
    # .env dosyası, .env.example dosyasından oluşturuluyor.
    - cp .env.example .env
    # Bağımlılıklar yükleniyor.
    - composer install
    # Key üretiliyor.
    - php artisan key:generate
    # Unit testler çalıştırılıyor.
    - php artisan test
    # PHPMD testi çalıştırılıyor
    - composer phpmd
    # PHP CodeSniffer testi çalıştırılıyor.
    - composer phpcs-src

deploy:
  stage: deploy
  environment: production
  script:
    # SSH key build ortamına ekleniyor.
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

    # Deploy işleri başlatılıyor
    - ~/.composer/vendor/bin/envoy run deploy --commit="$CI_COMMIT_SHA"
  only:
    - master
